### ISSUE TITLE
You are not allowed to transition images without acquiring them.

### ISSUE THREAD

**Issue by ratchetfreak** [Mervill/Tanagra#3]
https://github.com/Mervill/Tanagra/blob/9ecfc53c39d76f0c2c9188b6bd218a12c656fe0e/TanagraExample/ExampleRenderToWindow.cs#L201-L206

Here you transition the swapchain images without having Acquired them. This is not allowed.

> Use of a presentable image must occur only after the image is returned by vkAcquireNextImageKHR, and before it is presented by vkQueuePresentKHR. **This includes transitioning the image layout and rendering commands.**

You can instead set the old layout in `createCommandBuffer` to undefined. Transitioning away from `undefined` is always allowed and implies that you don't care about the existing data.

For more info see http://stackoverflow.com/q/37524032/731620

**Comment by Mervill** [comment]
Good catch! This is definitely the kind of thing I'm relying on the LunarG validator to catch at the moment. Might be useful to let the LunarG team know about this as well.

**Comment by ratchetfreak** [comment]
They know about it already.
